### ISSUE TITLE
Pin to ubuntu-24.04 instead of ubuntu-latest

### ISSUE THREAD

**Issue by hspaans** [hspaans/.github#144]
**Ubuntu-latest workflows will use Ubuntu-24.04 image**
In [10636](https://github.com/actions/runner-images/issues/10636) the upgrade to Ubuntu 24.04 is announced with possible breaking changes. This version of Ubuntu is used by the GitHub Action runners.

**Example**

Workflow that has `runs-on: ubuntu-latest`

```yaml
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
```

Workflow that has `runs-on: ubuntu-24.04`

```yaml
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-24.04
```

**Affected files**

- [x] #148
- [x] #150
- [x] #152
- [x] #154
- [x] #145
- [x] #155
- [x] #158
- [x] #160
