### ISSUE TITLE
Maintenance tasks - 2025 SoC

### ISSUE THREAD

**Issue by hspaans** [hspaans/.github#167]
**Actions**

- [ ] Drop `.github/wiki`
- [ ] Drop `pypa/gh-action-pip-audit` from GitHub Workflows
- [ ] Review GitHub Workflows with a "- cron:" entry
- [ ] Group Dependabot package-ecosystems
```yaml
---
version: 2
updates:
  - package-ecosystem: devcontainer
    directory: /
    schedule:
      interval: weekly
    groups:
      devcontainer:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
```
- [ ] Bump to Ansible 12 (release date 2025-07-15)
